# Generated by Django 5.1.1 on 2024-09-21 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggiesApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recipe_img',
            field=models.ImageField(blank=True, null=True, upload_to='recipeimg/'),
        ),
    ]
